# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
