# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_auto_20180818_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
