# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0004_auto_20180818_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
